//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpsonsWeb.GoTServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Character", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Character : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GoTServiceReference.GoTServiceSoap")]
    public interface GoTServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Hello", ReplyAction="*")]
        SimpsonsWeb.GoTServiceReference.HelloResponse Hello(SimpsonsWeb.GoTServiceReference.HelloRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCharactersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCharacters", ReplyAction="*")]
        SimpsonsWeb.GoTServiceReference.GetAllCharactersResponse GetAllCharacters(SimpsonsWeb.GoTServiceReference.GetAllCharactersRequest request);
        
        // CODEGEN: Generating message contract since element name lastName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchByLastName", ReplyAction="*")]
        SimpsonsWeb.GoTServiceReference.SearchByLastNameResponse SearchByLastName(SimpsonsWeb.GoTServiceReference.SearchByLastNameRequest request);
        
        // CODEGEN: Generating message contract since element name firstName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchByFirstName", ReplyAction="*")]
        SimpsonsWeb.GoTServiceReference.SearchByFirstNameResponse SearchByFirstName(SimpsonsWeb.GoTServiceReference.SearchByFirstNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Hello", Namespace="http://tempuri.org/", Order=0)]
        public SimpsonsWeb.GoTServiceReference.HelloRequestBody Body;
        
        public HelloRequest() {
        }
        
        public HelloRequest(SimpsonsWeb.GoTServiceReference.HelloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloRequestBody {
        
        public HelloRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimpsonsWeb.GoTServiceReference.HelloResponseBody Body;
        
        public HelloResponse() {
        }
        
        public HelloResponse(SimpsonsWeb.GoTServiceReference.HelloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloResult;
        
        public HelloResponseBody() {
        }
        
        public HelloResponseBody(string HelloResult) {
            this.HelloResult = HelloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCharactersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCharacters", Namespace="http://tempuri.org/", Order=0)]
        public SimpsonsWeb.GoTServiceReference.GetAllCharactersRequestBody Body;
        
        public GetAllCharactersRequest() {
        }
        
        public GetAllCharactersRequest(SimpsonsWeb.GoTServiceReference.GetAllCharactersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCharactersRequestBody {
        
        public GetAllCharactersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCharactersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCharactersResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimpsonsWeb.GoTServiceReference.GetAllCharactersResponseBody Body;
        
        public GetAllCharactersResponse() {
        }
        
        public GetAllCharactersResponse(SimpsonsWeb.GoTServiceReference.GetAllCharactersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCharactersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimpsonsWeb.GoTServiceReference.Character[] GetAllCharactersResult;
        
        public GetAllCharactersResponseBody() {
        }
        
        public GetAllCharactersResponseBody(SimpsonsWeb.GoTServiceReference.Character[] GetAllCharactersResult) {
            this.GetAllCharactersResult = GetAllCharactersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByLastNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByLastName", Namespace="http://tempuri.org/", Order=0)]
        public SimpsonsWeb.GoTServiceReference.SearchByLastNameRequestBody Body;
        
        public SearchByLastNameRequest() {
        }
        
        public SearchByLastNameRequest(SimpsonsWeb.GoTServiceReference.SearchByLastNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByLastNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lastName;
        
        public SearchByLastNameRequestBody() {
        }
        
        public SearchByLastNameRequestBody(string lastName) {
            this.lastName = lastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByLastNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByLastNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimpsonsWeb.GoTServiceReference.SearchByLastNameResponseBody Body;
        
        public SearchByLastNameResponse() {
        }
        
        public SearchByLastNameResponse(SimpsonsWeb.GoTServiceReference.SearchByLastNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByLastNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimpsonsWeb.GoTServiceReference.Character[] SearchByLastNameResult;
        
        public SearchByLastNameResponseBody() {
        }
        
        public SearchByLastNameResponseBody(SimpsonsWeb.GoTServiceReference.Character[] SearchByLastNameResult) {
            this.SearchByLastNameResult = SearchByLastNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByFirstNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByFirstName", Namespace="http://tempuri.org/", Order=0)]
        public SimpsonsWeb.GoTServiceReference.SearchByFirstNameRequestBody Body;
        
        public SearchByFirstNameRequest() {
        }
        
        public SearchByFirstNameRequest(SimpsonsWeb.GoTServiceReference.SearchByFirstNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByFirstNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstName;
        
        public SearchByFirstNameRequestBody() {
        }
        
        public SearchByFirstNameRequestBody(string firstName) {
            this.firstName = firstName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByFirstNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByFirstNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimpsonsWeb.GoTServiceReference.SearchByFirstNameResponseBody Body;
        
        public SearchByFirstNameResponse() {
        }
        
        public SearchByFirstNameResponse(SimpsonsWeb.GoTServiceReference.SearchByFirstNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByFirstNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimpsonsWeb.GoTServiceReference.Character[] SearchByFirstNameResult;
        
        public SearchByFirstNameResponseBody() {
        }
        
        public SearchByFirstNameResponseBody(SimpsonsWeb.GoTServiceReference.Character[] SearchByFirstNameResult) {
            this.SearchByFirstNameResult = SearchByFirstNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GoTServiceSoapChannel : SimpsonsWeb.GoTServiceReference.GoTServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GoTServiceSoapClient : System.ServiceModel.ClientBase<SimpsonsWeb.GoTServiceReference.GoTServiceSoap>, SimpsonsWeb.GoTServiceReference.GoTServiceSoap {
        
        public GoTServiceSoapClient() {
        }
        
        public GoTServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GoTServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoTServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoTServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpsonsWeb.GoTServiceReference.HelloResponse SimpsonsWeb.GoTServiceReference.GoTServiceSoap.Hello(SimpsonsWeb.GoTServiceReference.HelloRequest request) {
            return base.Channel.Hello(request);
        }
        
        public string Hello() {
            SimpsonsWeb.GoTServiceReference.HelloRequest inValue = new SimpsonsWeb.GoTServiceReference.HelloRequest();
            inValue.Body = new SimpsonsWeb.GoTServiceReference.HelloRequestBody();
            SimpsonsWeb.GoTServiceReference.HelloResponse retVal = ((SimpsonsWeb.GoTServiceReference.GoTServiceSoap)(this)).Hello(inValue);
            return retVal.Body.HelloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpsonsWeb.GoTServiceReference.GetAllCharactersResponse SimpsonsWeb.GoTServiceReference.GoTServiceSoap.GetAllCharacters(SimpsonsWeb.GoTServiceReference.GetAllCharactersRequest request) {
            return base.Channel.GetAllCharacters(request);
        }
        
        public SimpsonsWeb.GoTServiceReference.Character[] GetAllCharacters() {
            SimpsonsWeb.GoTServiceReference.GetAllCharactersRequest inValue = new SimpsonsWeb.GoTServiceReference.GetAllCharactersRequest();
            inValue.Body = new SimpsonsWeb.GoTServiceReference.GetAllCharactersRequestBody();
            SimpsonsWeb.GoTServiceReference.GetAllCharactersResponse retVal = ((SimpsonsWeb.GoTServiceReference.GoTServiceSoap)(this)).GetAllCharacters(inValue);
            return retVal.Body.GetAllCharactersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpsonsWeb.GoTServiceReference.SearchByLastNameResponse SimpsonsWeb.GoTServiceReference.GoTServiceSoap.SearchByLastName(SimpsonsWeb.GoTServiceReference.SearchByLastNameRequest request) {
            return base.Channel.SearchByLastName(request);
        }
        
        public SimpsonsWeb.GoTServiceReference.Character[] SearchByLastName(string lastName) {
            SimpsonsWeb.GoTServiceReference.SearchByLastNameRequest inValue = new SimpsonsWeb.GoTServiceReference.SearchByLastNameRequest();
            inValue.Body = new SimpsonsWeb.GoTServiceReference.SearchByLastNameRequestBody();
            inValue.Body.lastName = lastName;
            SimpsonsWeb.GoTServiceReference.SearchByLastNameResponse retVal = ((SimpsonsWeb.GoTServiceReference.GoTServiceSoap)(this)).SearchByLastName(inValue);
            return retVal.Body.SearchByLastNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpsonsWeb.GoTServiceReference.SearchByFirstNameResponse SimpsonsWeb.GoTServiceReference.GoTServiceSoap.SearchByFirstName(SimpsonsWeb.GoTServiceReference.SearchByFirstNameRequest request) {
            return base.Channel.SearchByFirstName(request);
        }
        
        public SimpsonsWeb.GoTServiceReference.Character[] SearchByFirstName(string firstName) {
            SimpsonsWeb.GoTServiceReference.SearchByFirstNameRequest inValue = new SimpsonsWeb.GoTServiceReference.SearchByFirstNameRequest();
            inValue.Body = new SimpsonsWeb.GoTServiceReference.SearchByFirstNameRequestBody();
            inValue.Body.firstName = firstName;
            SimpsonsWeb.GoTServiceReference.SearchByFirstNameResponse retVal = ((SimpsonsWeb.GoTServiceReference.GoTServiceSoap)(this)).SearchByFirstName(inValue);
            return retVal.Body.SearchByFirstNameResult;
        }
    }
}
